# Generated by Django 5.2.4 on 2025-08-22 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('type', models.CharField(choices=[('M', 'MAN'), ('F', 'FEMALE')], max_length=2)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
